### PR TITLE
added glfw3 to make raylib v2.5.0 work. added tetris example implemen…

### PR DESCRIPTION
**Pull request by daveheitzman**
…tation

### CODE REVIEW

**Comment by aldrinmartoq** [comment]
Hi @daveheitzman, thanks for your PR!

I'm reviewing now. Nice Tetris implementation ;-)

Can you tell me platforms are you using?

**Comment by daveheitzman** [comment]
Thanks. This was done on Ubuntu 18.04, ruby 2.6.3.

**Comment by aldrinmartoq** [comment]
@daveheitzman Ok, I think adding glfw3 as a runtime/dev dependency is not good, because it would mean the end user must install another DLL/library on its system.

Also, that library should automatically be loaded when we load libraylib.so, adding the gem glfw3 as a dependency is for the cases when we need to call glfw3 directly.

I have built raylib on ubuntu following the [wiki instructions](https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux):
- Both 2.5.0 and HEAD runs fine (using the embedded glfw), and the raylib-ruby wrapper works fine too
- I could not make raylib work using an external glfw (both apt installed and the source installation). I get `undefined reference to glfwGetGamepadState` while compiling the examples.

So please, make this 2 patches: one for the tetris game, and another for the glfw issue.

I guess there is another way to solve your glfw issue… Can you share your build instructions? Probably there is a bug in the raylib build scripts, can you check if the library has a reference to glfw with `ldd /usr/local/lib/libraylib.so`?

**Comment by daveheitzman** [comment]
Will do.

**Comment by daveheitzman** [comment]
this is on ubuntu 16.04. 

After removing the glfw3 dependency from the gem, if I try to run the ruby tetris, I get: 
...
screen_w: 800 screen_h: 450
INFO: Initializing raylib 2.5
ruby: symbol lookup error: /usr/local/lib/libraylib.so: undefined symbol: XInitThreads

gruen@gruen-ThinkPad-E550:~/code/raylib/src$ ldd /usr/local/lib/libraylib.so
	linux-vdso.so.1 =>  (0x00007ffcb0b3e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007faa33e58000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007faa33b4f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007faa33932000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007faa3372e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007faa34580000)

I built raylib using the makefile set with

RAYLIB_LIBTYPE       ?= SHARED
USE_EXTERNAL_GLFW    ?= FALSE

Thanks.

**Comment by aldrinmartoq** [comment]
Right, I can replicate your problem (just built raylib using `make RAYLIB_LIBTYPE=SHARED` and checked with `ldd /usr/loca/lib/libraylib.so`). Well, it seems **there is a bug in the raylib makefile scripts** because the generated libraylib.so does not references libX11 (among other required libs). When you added glfw3 as a dependency, that gem unnecessarily loaded libglfw3, which loaded libX11… but that's not a solution.

You have 2 options:
1. Rebuild raylib using cmake. You can check the wiki, but the build is fairly simple in ubuntu:
```
sudo apt install build-essential
sudo apt install cmake
sudo apt install libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
wget https://github.com/raysan5/raylib/archive/2.5.0.tar.gz
tar xvfz 2.5.0.tar.gz
cd raylib-2.5.0
mkdir build
cd build
cmake -DSHARED=ON -DSTATIC=ON ..    # note the two dots
make
sudo make install
```
2. Another option is to just use the binaries provided in the [releases page](https://github.com/raysan5/raylib/releases) and download the [linux build](https://github.com/raysan5/raylib/releases/download/2.5.0/raylib-2.5.0-Linux-amd64.tar.gz). Then move the files to /usr/local/

I have to close this PR and wait for the one with only the tetris version.

**Comment by daveheitzman** [comment]
Your last post was right on. I was able to get it working by 1. removing the glfw3 gem dependency, and 2. Download and install the pre-built distributions of raylib. 
Now the ruby tetris works locally. I will submit a PR. 
Thanks for your help.

**Pull request closed without merging**
